# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/z_interp_divider/z_interp_divider.xci
# IP: The module: 'z_interp_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/z_interp_divider/z_interp_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_interp_divider'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/z_interp_divider/z_interp_divider.xci
# IP: The module: 'z_interp_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/z_interp_divider/z_interp_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_interp_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
