# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/demo_rom2/demo_rom2.xci
# IP: The module: 'demo_rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/demo_rom2/demo_rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_rom2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/demo_rom2/demo_rom2.xci
# IP: The module: 'demo_rom2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/demo_rom2/demo_rom2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_rom2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
