# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/model_rotation/model_rotation.xci
# IP: The module: 'model_rotation' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/model_rotation/model_rotation_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'model_rotation'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/model_rotation/model_rotation.xci
# IP: The module: 'model_rotation' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/tabletop_hologram/tabletop_hologram.srcs/sources_1/ip/model_rotation/model_rotation_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'model_rotation'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
