# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/adamp/Desktop/Fall 2019/6.111/6111/tabletop_hologram.srcs/sources_1/ip/demo_rom1/demo_rom1.xci
# IP: The module: 'demo_rom1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adamp/Desktop/Fall 2019/6.111/6111/tabletop_hologram.srcs/sources_1/ip/demo_rom1/demo_rom1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_rom1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/adamp/Desktop/Fall 2019/6.111/6111/tabletop_hologram.srcs/sources_1/ip/demo_rom1/demo_rom1.xci
# IP: The module: 'demo_rom1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adamp/Desktop/Fall 2019/6.111/6111/tabletop_hologram.srcs/sources_1/ip/demo_rom1/demo_rom1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_rom1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
